name: Daily Commit

on:
  schedule:
    # - cron: '0 23 * * *' # Runs every day at 11 pm
     - cron: '0 6 * * *' # Runs every day at 6 AM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy
        python -m pip install pandas
        # pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python main.py

    - name: Commit Changes
      run: |
        git config --global user.email "jjfrisch@outlook.com"
        git config --global user.name "JJfrisch"
        git commit -am "Daily Commit"
        git push
